### ISSUE TITLE
Bring coverage back

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/axum-login#108]
I've removed coverage for the time being as `tarpaulin` doesn't seem to be able to properly instrument the integration test. It'd be nice to introduce it again at some point. Note that we may also want to explore different approaches to testing that make this easier.

**Comment by czocher** [comment]
From my experience with https://github.com/cljoly/rusqlite_migration/tree/master we moved the integration tests to a separate subcrate in the project workspace and added:

```
[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true
```

then `tarpaulin` handled it without much issue. We can probably copy some CI ideas from there, since @cljoly is a specialist in proper CI/testing.

Some other ideas that we might want to do here:
1. Test no features and `--all-features` which solves problems with possible non-additive features in the future.
2. Mutation testing.

See https://github.com/cljoly/rusqlite_migration/blob/master/.github/workflows/ci.yml for details.

**Comment by czocher** [comment]
I had a quick look at this and the main issue here is that we're not executing any code directly - the current integration test sets up the sqlite example as a subprocess, tarpaulin won't be able to see the calls to that subprocess.

I we can try to use https://docs.rs/axum-test/latest/axum_test/ to create the tests instead, it should work then, but we shouldn't base it on the sqlite example, but do one (or more) defined test cases with some in-memory session and user storage instead of sqlite.

**Comment by maxcountryman** [comment]
I think it's also worth expanding the unit-style tests with test modules where appropriate. I've started to do this with `tower-sessions` and its service module, for example.
